import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import QueryProvider from "@/providers/query-provider";

const figtree = Figtree({
    subsets: ["latin"],
    weight: ["400", "500", "600", "800"],
    variable: "--font-figtree",
});

export const metadata: Metadata = {
    title: "AMHS Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${figtree.className} antialiased flex min-h-screen w-screen overflow-x-hidden bg-gray-100`}
            >
                <QueryProvider>
                  {children}
                </QueryProvider>
                <Toaster />
            </body>
        </html>
    );
}
